---
exclude: ""
repos:
  # Set the list of basic git hooks to find and fix common problems in the current working tree.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Use the static code checker to find and fix logical errors in python source code.
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        language_version: python3
        args:
          - --fix
      - id: ruff-format
 